/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutTemplatesRouteImport } from './routes/_layout/templates'
import { Route as LayoutSubscriptionsRouteImport } from './routes/_layout/subscriptions'
import { Route as LayoutWorkshopsCreateRouteImport } from './routes/_layout/workshops/create'
import { Route as LayoutWorkshopsWorkshopIdRouteImport } from './routes/_layout/workshops/$workshopId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesRoute = LayoutTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubscriptionsRoute = LayoutSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkshopsCreateRoute = LayoutWorkshopsCreateRouteImport.update({
  id: '/workshops/create',
  path: '/workshops/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkshopsWorkshopIdRoute =
  LayoutWorkshopsWorkshopIdRouteImport.update({
    id: '/workshops/$workshopId',
    path: '/workshops/$workshopId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/subscriptions': typeof LayoutSubscriptionsRoute
  '/templates': typeof LayoutTemplatesRoute
  '/users': typeof LayoutUsersRoute
  '/workshops/$workshopId': typeof LayoutWorkshopsWorkshopIdRoute
  '/workshops/create': typeof LayoutWorkshopsCreateRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/subscriptions': typeof LayoutSubscriptionsRoute
  '/templates': typeof LayoutTemplatesRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
  '/workshops/$workshopId': typeof LayoutWorkshopsWorkshopIdRoute
  '/workshops/create': typeof LayoutWorkshopsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/templates': typeof LayoutTemplatesRoute
  '/_layout/subscriptions': typeof LayoutSubscriptionsRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/workshops/$workshopId': typeof LayoutWorkshopsWorkshopIdRoute
  '/_layout/workshops/create': typeof LayoutWorkshopsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/templates'
    | '/users'
    | '/workshops/$workshopId'
    | '/workshops/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/subscriptions'
    | '/templates'
    | '/users'
    | '/'
    | '/workshops/$workshopId'
    | '/workshops/create'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/subscriptions'
    | '/_layout/templates'
    | '/_layout/users'
    | '/_layout/'
    | '/_layout/workshops/$workshopId'
    | '/_layout/workshops/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/subscriptions': {
      id: '/_layout/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof LayoutSubscriptionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates': {
      id: '/_layout/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof LayoutTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workshops/create': {
      id: '/_layout/workshops/create'
      path: '/workshops/create'
      fullPath: '/workshops/create'
      preLoaderRoute: typeof LayoutWorkshopsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workshops/$workshopId': {
      id: '/_layout/workshops/$workshopId'
      path: '/workshops/$workshopId'
      fullPath: '/workshops/$workshopId'
      preLoaderRoute: typeof LayoutWorkshopsWorkshopIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutTemplatesRoute: typeof LayoutTemplatesRoute
  LayoutSubscriptionsRoute: typeof LayoutSubscriptionsRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutWorkshopsWorkshopIdRoute: typeof LayoutWorkshopsWorkshopIdRoute
  LayoutWorkshopsCreateRoute: typeof LayoutWorkshopsCreateRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutTemplatesRoute: LayoutTemplatesRoute,
  LayoutSubscriptionsRoute: LayoutSubscriptionsRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutWorkshopsWorkshopIdRoute: LayoutWorkshopsWorkshopIdRoute,
  LayoutWorkshopsCreateRoute: LayoutWorkshopsCreateRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
